# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_ventilador.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart_ventilador.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16smart_ventilador.proto\"\"\n\x10VentiladorStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x85\x01\n\nVentilador\x12\x39\n\x0fligarVentilador\x12\x11.VentiladorStatus\x1a\x11.VentiladorStatus\"\x00\x12<\n\x12\x64\x65sligarVentilador\x12\x11.VentiladorStatus\x1a\x11.VentiladorStatus\"\x00\x62\x06proto3'
)




_VENTILADORSTATUS = _descriptor.Descriptor(
  name='VentiladorStatus',
  full_name='VentiladorStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='VentiladorStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['VentiladorStatus'] = _VENTILADORSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VentiladorStatus = _reflection.GeneratedProtocolMessageType('VentiladorStatus', (_message.Message,), {
  'DESCRIPTOR' : _VENTILADORSTATUS,
  '__module__' : 'smart_ventilador_pb2'
  # @@protoc_insertion_point(class_scope:VentiladorStatus)
  })
_sym_db.RegisterMessage(VentiladorStatus)



_VENTILADOR = _descriptor.ServiceDescriptor(
  name='Ventilador',
  full_name='Ventilador',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=63,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='ligarVentilador',
    full_name='Ventilador.ligarVentilador',
    index=0,
    containing_service=None,
    input_type=_VENTILADORSTATUS,
    output_type=_VENTILADORSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='desligarVentilador',
    full_name='Ventilador.desligarVentilador',
    index=1,
    containing_service=None,
    input_type=_VENTILADORSTATUS,
    output_type=_VENTILADORSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VENTILADOR)

DESCRIPTOR.services_by_name['Ventilador'] = _VENTILADOR

# @@protoc_insertion_point(module_scope)
