# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_obj.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart_obj.proto',
  package='smartobj',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fsmart_obj.proto\x12\x08smartobj\"Y\n\x0bSmartObject\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\"\n\x04type\x18\x03 \x01(\x0e\x32\x14.smartobj.TypeObject\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t*&\n\nTypeObject\x12\n\n\x06SENSOR\x10\x00\x12\x0c\n\x08\x41\x43TUATOR\x10\x01\x62\x06proto3')
)

_TYPEOBJECT = _descriptor.EnumDescriptor(
  name='TypeObject',
  full_name='smartobj.TypeObject',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SENSOR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTUATOR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=120,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_TYPEOBJECT)

TypeObject = enum_type_wrapper.EnumTypeWrapper(_TYPEOBJECT)
SENSOR = 0
ACTUATOR = 1



_SMARTOBJECT = _descriptor.Descriptor(
  name='SmartObject',
  full_name='smartobj.SmartObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='smartobj.SmartObject.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='smartobj.SmartObject.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='smartobj.SmartObject.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='smartobj.SmartObject.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=118,
)

_SMARTOBJECT.fields_by_name['type'].enum_type = _TYPEOBJECT
DESCRIPTOR.message_types_by_name['SmartObject'] = _SMARTOBJECT
DESCRIPTOR.enum_types_by_name['TypeObject'] = _TYPEOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmartObject = _reflection.GeneratedProtocolMessageType('SmartObject', (_message.Message,), dict(
  DESCRIPTOR = _SMARTOBJECT,
  __module__ = 'smart_obj_pb2'
  # @@protoc_insertion_point(class_scope:smartobj.SmartObject)
  ))
_sym_db.RegisterMessage(SmartObject)


# @@protoc_insertion_point(module_scope)
