# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_portao.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart_portao.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12smart_portao.proto\"\x1e\n\x0cPortaoStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32g\n\x06Portao\x12-\n\x0b\x61\x62rirPortao\x12\r.PortaoStatus\x1a\r.PortaoStatus\"\x00\x12.\n\x0c\x66\x65\x63harPortao\x12\r.PortaoStatus\x1a\r.PortaoStatus\"\x00\x62\x06proto3'
)




_PORTAOSTATUS = _descriptor.Descriptor(
  name='PortaoStatus',
  full_name='PortaoStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='PortaoStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['PortaoStatus'] = _PORTAOSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortaoStatus = _reflection.GeneratedProtocolMessageType('PortaoStatus', (_message.Message,), {
  'DESCRIPTOR' : _PORTAOSTATUS,
  '__module__' : 'smart_portao_pb2'
  # @@protoc_insertion_point(class_scope:PortaoStatus)
  })
_sym_db.RegisterMessage(PortaoStatus)



_PORTAO = _descriptor.ServiceDescriptor(
  name='Portao',
  full_name='Portao',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=54,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='abrirPortao',
    full_name='Portao.abrirPortao',
    index=0,
    containing_service=None,
    input_type=_PORTAOSTATUS,
    output_type=_PORTAOSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='fecharPortao',
    full_name='Portao.fecharPortao',
    index=1,
    containing_service=None,
    input_type=_PORTAOSTATUS,
    output_type=_PORTAOSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PORTAO)

DESCRIPTOR.services_by_name['Portao'] = _PORTAO

# @@protoc_insertion_point(module_scope)
